spring:
  application:
    name: dnd-AI-generator
  ai:
    openai:
      api-key:
web:
  timeout: 60s
  url: https://api.openai.com/v1/chat/completions
  openai:
    api-key: ${spring.ai.openai.api-key}

rest:
  timeout: 60s
  url: https://www.dnd5eapi.co
  spells: /api/2014/classes/{index}/spellcasting
  spell-book: /api/2014/spells?level={level}&school={school}

threads:
  core-pool-size: 4
  max-pool-size: 8
  queue-capacity: 50

